jasypt:
   encryptor:
      password: secreto
      algorithm: PBEWithMD5AndDES

server:
   port: 8085
   servlet:
      context-path: /ProyectoADN
      session:
         timeout: 21600s

spring:
   h2:
      console:
         enabled: true
         path: /h2
   datasource:
      #url: jdbc:h2:file:~/ADNCEIBA
      username: root
      password: ENC(+au5NL8C30E0VeJlGp7GJw==)
      #driverClassName: org.h2.Driver
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: org.h2.Driver
      jdbcUrl: jdbc:h2:file:~/ADNCEIBAV1_11
      hikari:
         poolName: pool
   jpa:
      properties:
         hibernate:
            dialect: org.hibernate.dialect.H2Dialect
      hibernate:
         connection:
            providerClass: com.zaxxer.hikari.hibernate.HikariConnectionProvider
         ddlAuto: none
      showSql: true
      openInView: false

persistencia:
   type: jpa
